### ISSUE TITLE
TcpView snapshots

### ISSUE THREAD

**Issue by chipmunk-sm** [chipmunk-sm/tcpview#1]
![screenshot_201708111](https://user-images.githubusercontent.com/29524958/29194415-231f2b9e-7e32-11e7-8c94-8eac6ea0bf98.png)

**Comment by intika** [comment]
Just a little ping, amazing little app ! thank you for your work and for sharing it i am sad i did not saw it before starting to work on this https://github.com/Intika-Linux-Network/Network-Watcher ... i may switch my project to be based on yours :)
