### ISSUE TITLE
Clicking on "Names" causes 100% cpu usage

### ISSUE THREAD

**Issue by frinnst** [chipmunk-sm/tcpview#3]
Seems this kills the tcpview :-)

Built under qt 5.9.1.  Should be easily reproducable

	linux-vdso.so.1 (0x00007fff1f297000)
	libuuid.so.1 => /lib/libuuid.so.1 (0x00007f50051c3000)
	libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f5004b86000)
	libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f500464c000)
	libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f5004093000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f5003e29000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f5003c0c000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f500388c000)
	libm.so.6 => /lib/libm.so.6 (0x00007f5003588000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5003371000)
	libc.so.6 => /lib/libc.so.6 (0x00007f5002fd3000)
	/lib/ld-linux-x86-64.so.2 (0x00007f50053c8000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f5002d9e000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f5002b0a000)
	libz.so.1 => /lib/libz.so.1 (0x00007f50028f3000)
	libdl.so.2 => /lib/libdl.so.2 (0x00007f50026ef000)
	libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0x00007f50024ed000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f50021dc000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f5001fb1000)
	libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x00007f5001dae000)
	libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0x00007f5001ba7000)
	libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0x00007f50019a4000)
	libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x00007f500179e000)
	libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0x00007f500159c000)
	libglapi.so.0 => /usr/lib/libglapi.so.0 (0x00007f500136c000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f5001169000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f5000f63000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007f5000d61000)
	libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x00007f5000b48000)
	libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x00007f5000943000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f500073d000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f500052b000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f50001f0000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f4ffffcb000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f4fffdc7000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f4fffbc1000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007f4fff9b1000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f4fff70e000)
	libpcre.so.1 => /lib/libpcre.so.1 (0x00007f4fff49c000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f4fff28b000)

**Comment by chipmunk-sm** [comment]
Well, I'll try 5.9 :)

Seems like something wrong with "pkexec"

In any way , it will be helpful if you could show output
`$ uname -a`
`$ lsb_release -a`

**Comment by chipmunk-sm** [comment]
click "names" -> look at password prompt and say "no way" - > click "cancel" -> catch 100% cpu usage. Right? 

Ok.  Fix will be available "as soon as possible." XD

**Comment by frinnst** [comment]
Nothing happens when i click "names". Is it supposed to launch some sudo gui thingy or something?

**Comment by chipmunk-sm** [comment]
Button "names" call "pkexec" 
https://www.freedesktop.org/software/polkit/docs/0.105/pkexec.1.html

In your case, perhaps **pkexec** is missing or has some restrictions to start a dialog with password request.
First part easy check with terminal 
`pkexec`
Second part..., at this moment I has no idea how to resolve system restrictions with 'policykit-1' 

Code work perfect under Kubuntu 16.10 , but under 17.04  pkexec probably return some result immediately and waitForStarted(); do not want block program as expected . 
```
...
    m_rootResolver.start( "pkexec " + QCoreApplication::applicationFilePath() + " --rootmodule");
    m_rootResolver.waitForStarted();
...
```

**Comment by frinnst** [comment]
I don't use ubuntu and my distribution does not ship with polkit :-)

Maybe just fail a bit more gracefully if it's not available?

**Comment by chipmunk-sm** [comment]
Of course, the new version will be published soon.

**Comment by chipmunk-sm** [comment]
Fixed. Release 2.0.0.2

Added support for:
"/usr/bin/pkexec";
"/usr/bin/kdesudo";
"/usr/bin/gksudo";
"/usr/bin/kdesu";
"/usr/bin/gksu";
