### ISSUE TITLE
It would be perfect to have color notification just like windows tcpview.

### ISSUE THREAD

**Issue by springzfx** [chipmunk-sm/tcpview#6]
As the title says.

**Comment by chipmunk-sm** [comment]
Sorry, I'm busy with other projects. I hope next year I will rewrite this completely with normal architecture with a lot of features. In any case, thanks for your attention to this project )

**Comment by sanawu** [comment]
What is a normal architecture?

**Comment by chipmunk-sm** [comment]
![screen](https://user-images.githubusercontent.com/29524958/118386224-7e994e00-b605-11eb-8a24-2feef8a62815.png)

Ready #8
